Public Class Form1
    Private Sub Form1_KeyDown(sender As Object, e As KeyEventArgs) Handles Me.KeyDown
        '   Me.BackColor = Color.Black
        Select Case e.KeyCode
            Case Keys.A
                movexy(-10, 0, Avatar)
                ChangeDirection(Avatar, "E")
            Case Keys.D
                ChangeDirection(Avatar, "W")
                movexy(10, 0, Avatar)
            Case Keys.W
                ChangeDirection(Avatar, "W")
                movexy(0, -10, Avatar)
            Case Keys.S
                ChangeDirection(Avatar, "E")
                movexy(-0, 10, Avatar)
            Case Keys.J

            Case Keys.Space
                Add(Avatar, B1, "direction", 10)
                ' Add(Avatar, B1, "N", 5)
                'Add(Avatar, "jump", 20)
                '(Enemy1, "Follow", 5)
        End Select
        Debug.Print(Avatar.Location.X)
        Me.Refresh()
    End Sub


    Private Sub Timer2_Tick(sender As Object, e As EventArgs) Handles Timer2.Tick
        Animate()
        LeftRight(Enemy1)
        LeftRight1(Enemy2)
        LeftRight2(Enemy3)
        LeftRight3(Enemy4)
        LeftRight4(Enemy5)
        LeftRight5(Enemy6)
    End Sub

    Private Sub Form1_Load(sender As Object, e As EventArgs) Handles Me.Load
        SetControls(Me.Controls)
    End Sub
    Sub Collision(obj1 As PictureBox, obj2 As PictureBox)
        Label1.Text = obj1.Name & "," & obj2.Name
        If obj2.Name.Contains("Enemy") AndAlso obj1.Name.Contains("B1") Then
            obj2.Visible = False
            obj1.Visible = False
        End If
        If obj1.Name.Contains("B1") AndAlso obj2.Name.Contains("PictureBox") Then
            obj1.Visible = False
        End If
    End Sub
    Sub LeftRight(obj As PictureBox)
        Dim index As Integer
        Dim points(32) As Point
        points(0) = New Point(-5, 0)
        points(1) = New Point(-5, 0)
        points(2) = New Point(-5, 0)
        points(3) = New Point(-5, 0)
        points(4) = New Point(-5, 0)
        points(5) = New Point(-5, 0)
        points(6) = New Point(-5, 0)
        points(7) = New Point(-5, 0)
        points(8) = New Point(0, 5)
        points(9) = New Point(0, 5)
        points(10) = New Point(0, 5)
        points(11) = New Point(0, 5)
        points(12) = New Point(0, 5)
        points(13) = New Point(0, 5)
        points(14) = New Point(0, 5)
        points(15) = New Point(0, 5)
        points(16) = New Point(5, 0)
        points(17) = New Point(5, 0)
        points(18) = New Point(5, 0)
        points(19) = New Point(5, 0)
        points(20) = New Point(5, 0)
        points(21) = New Point(5, 0)
        points(22) = New Point(5, 0)
        points(23) = New Point(5, 0)
        points(24) = New Point(0, -5)
        points(25) = New Point(0, -5)
        points(26) = New Point(0, -5)
        points(27) = New Point(0, -5)
        points(28) = New Point(0, -5)
        points(29) = New Point(0, -5)
        points(30) = New Point(0, -5)
        points(31) = New Point(0, -5)
        'Don't change after here
        Integer.TryParse(obj.Tag, index)
        '  obj.Location = New Point(obj.Location.X + points(index).X, obj.Location.Y + points(index).Y)
        movexy(points(index).X, points(index).Y, obj)
        index = (index + 1) Mod points.Length
        obj.Tag = index
    End Sub
    Sub LeftRight1(obj As PictureBox)
        Dim index As Integer
        Dim points(32) As Point
        points(0) = New Point(-5, 0)
        points(1) = New Point(-5, 0)
        points(2) = New Point(-5, 0)
        points(3) = New Point(-5, 0)
        points(4) = New Point(-5, 0)
        points(5) = New Point(-5, 0)
        points(6) = New Point(-5, 0)
        points(7) = New Point(-5, 0)
        points(8) = New Point(0, -5)
        points(9) = New Point(0, -5)
        points(10) = New Point(0, -5)
        points(11) = New Point(0, -5)
        points(12) = New Point(0, -5)
        points(13) = New Point(0, -5)
        points(14) = New Point(0, -5)
        points(15) = New Point(0, -5)
        points(16) = New Point(5, 0)
        points(17) = New Point(5, 0)
        points(18) = New Point(5, 0)
        points(19) = New Point(5, 0)
        points(20) = New Point(5, 0)
        points(21) = New Point(5, 0)
        points(22) = New Point(5, 0)
        points(23) = New Point(5, 0)
        points(24) = New Point(0, 5)
        points(25) = New Point(0, 5)
        points(26) = New Point(0, 5)
        points(27) = New Point(0, 5)
        points(28) = New Point(0, 5)
        points(29) = New Point(0, 5)
        points(30) = New Point(0, 5)
        points(31) = New Point(0, 5)
        'Don't change after here
        Integer.TryParse(obj.Tag, index)
        '  obj.Location = New Point(obj.Location.X + points(index).X, obj.Location.Y + points(index).Y)
        movexy(points(index).X, points(index).Y, obj)
        index = (index + 1) Mod points.Length
        obj.Tag = index
    End Sub
    Sub LeftRight2(obj As PictureBox)
        Dim index As Integer
        Dim points(100) As Point
        points(0) = New Point(10, 0)
        points(1) = New Point(10, 0)
        points(2) = New Point(10, 0)
        points(3) = New Point(10, 0)
        points(4) = New Point(10, 0)
        points(5) = New Point(10, 0)
        points(6) = New Point(10, 0)
        points(7) = New Point(10, 0)
        points(8) = New Point(10, 0)
        points(9) = New Point(10, 0)
        points(10) = New Point(10, 0)
        points(11) = New Point(10, 0)
        points(12) = New Point(10, 0)
        points(13) = New Point(10, 0)
        points(14) = New Point(10, 0)
        points(15) = New Point(10, 0)
        points(16) = New Point(10, 0)
        points(17) = New Point(10, 0)
        points(18) = New Point(10, 0)
        points(19) = New Point(10, 0)
        points(20) = New Point(0, 10)
        points(21) = New Point(0, 10)
        points(22) = New Point(0, 10)
        points(23) = New Point(0, 10)
        points(24) = New Point(0, 10)
        points(25) = New Point(0, 10)
        points(26) = New Point(0, 10)
        points(27) = New Point(0, 10)
        points(28) = New Point(0, 10)
        points(29) = New Point(0, 10)
        points(30) = New Point(0, 10)
        points(31) = New Point(0, 10)
        points(32) = New Point(0, 10)
        points(33) = New Point(0, 10)
        points(34) = New Point(0, 10)
        points(35) = New Point(0, 10)
        points(36) = New Point(0, 10)
        points(37) = New Point(0, 10)
        points(38) = New Point(0, 10)
        points(39) = New Point(0, 10)
        points(40) = New Point(0, 10)
        points(41) = New Point(0, 10)
        points(42) = New Point(0, 10)
        points(43) = New Point(0, 10)
        points(44) = New Point(0, 10)
        points(45) = New Point(0, 10)
        points(46) = New Point(0, 10)
        points(47) = New Point(0, 10)
        points(48) = New Point(0, 10)
        points(49) = New Point(0, 10)
        points(50) = New Point(-10, 0)
        points(51) = New Point(-10, 0)
        points(52) = New Point(-10, 0)
        points(53) = New Point(-10, 0)
        points(54) = New Point(-10, 0)
        points(55) = New Point(-10, 0)
        points(56) = New Point(-10, 0)
        points(57) = New Point(-10, 0)
        points(58) = New Point(-10, 0)
        points(59) = New Point(-10, 0)
        points(60) = New Point(-10, 0)
        points(61) = New Point(-10, 0)
        points(62) = New Point(-10, 0)
        points(63) = New Point(-10, 0)
        points(64) = New Point(-10, 0)
        points(65) = New Point(-10, 0)
        points(66) = New Point(-10, 0)
        points(67) = New Point(-10, 0)
        points(68) = New Point(-10, 0)
        points(69) = New Point(-10, 0)
        points(70) = New Point(0, -10)
        points(71) = New Point(0, -10)
        points(72) = New Point(0, -10)
        points(73) = New Point(0, -10)
        points(74) = New Point(0, -10)
        points(75) = New Point(0, -10)
        points(76) = New Point(0, -10)
        points(77) = New Point(0, -10)
        points(78) = New Point(0, -10)
        points(79) = New Point(0, -10)
        points(80) = New Point(0, -10)
        points(81) = New Point(0, -10)
        points(82) = New Point(0, -10)
        points(83) = New Point(0, -10)
        points(84) = New Point(0, -10)
        points(85) = New Point(0, -10)
        points(86) = New Point(0, -10)
        points(87) = New Point(0, -10)
        points(88) = New Point(0, -10)
        points(89) = New Point(0, -10)
        points(90) = New Point(0, -10)
        points(91) = New Point(0, -10)
        points(92) = New Point(0, -10)
        points(93) = New Point(0, -10)
        points(94) = New Point(0, -10)
        points(95) = New Point(0, -10)
        points(96) = New Point(0, -10)
        points(97) = New Point(0, -10)
        points(98) = New Point(0, -10)
        points(99) = New Point(0, -10)
        'Don't change after here
        Integer.TryParse(obj.Tag, index)
        '  obj.Location = New Point(obj.Location.X + points(index).X, obj.Location.Y + points(index).Y)
        movexy(points(index).X, points(index).Y, obj)
        index = (index + 1) Mod points.Length
        obj.Tag = index
    End Sub
    Sub LeftRight3(obj As PictureBox)
        Dim index As Integer
        Dim points(103) As Point
        points(0) = New Point(0, 10)
        points(1) = New Point(0, 10)
        points(2) = New Point(0, 10)
        points(3) = New Point(0, 10)
        points(4) = New Point(0, 10)
        points(5) = New Point(0, 10)
        points(6) = New Point(0, 10)
        points(7) = New Point(0, 10)
        points(8) = New Point(0, 10)
        points(9) = New Point(0, 10)
        points(10) = New Point(0, 10)
        points(11) = New Point(0, 10)
        points(12) = New Point(0, 10)
        points(13) = New Point(0, 10)
        points(14) = New Point(0, 10)
        points(15) = New Point(0, 10)
        points(16) = New Point(0, 10)
        points(17) = New Point(0, 10)
        points(18) = New Point(0, 10)
        points(19) = New Point(0, 10)
        points(20) = New Point(0, 10)
        points(21) = New Point(0, 10)
        points(22) = New Point(0, 10)
        points(23) = New Point(0, 10)
        points(24) = New Point(0, 10)
        points(25) = New Point(0, 10)
        points(26) = New Point(0, 10)
        points(27) = New Point(0, 10)
        points(28) = New Point(0, 10)
        points(29) = New Point(0, 10)
        points(30) = New Point(-10, 0)
        points(31) = New Point(-10, 0)
        points(32) = New Point(-10, 0)
        points(33) = New Point(-10, 0)
        points(34) = New Point(-10, 0)
        points(35) = New Point(-10, 0)
        points(36) = New Point(-10, 0)
        points(37) = New Point(-10, 0)
        points(39) = New Point(-10, 0)
        points(40) = New Point(-10, 0)
        points(41) = New Point(-10, 0)
        points(42) = New Point(-10, 0)
        points(43) = New Point(-10, 0)
        points(44) = New Point(-10, 0)
        points(45) = New Point(-10, 0)
        points(46) = New Point(-10, 0)
        points(47) = New Point(-10, 0)
        points(48) = New Point(-10, 0)
        points(49) = New Point(-10, 0)
        points(50) = New Point(-10, 0)
        points(51) = New Point(-10, 0)
        points(52) = New Point(0, -10)
        points(53) = New Point(0, -10)
        points(54) = New Point(0, -10)
        points(55) = New Point(0, -10)
        points(56) = New Point(0, -10)
        points(57) = New Point(0, -10)
        points(58) = New Point(0, -10)
        points(59) = New Point(0, -10)
        points(60) = New Point(0, -10)
        points(61) = New Point(0, -10)
        points(62) = New Point(0, -10)
        points(63) = New Point(0, -10)
        points(64) = New Point(0, -10)
        points(65) = New Point(0, -10)
        points(66) = New Point(0, -10)
        points(67) = New Point(0, -10)
        points(68) = New Point(0, -10)
        points(69) = New Point(0, -10)
        points(70) = New Point(0, -10)
        points(71) = New Point(0, -10)
        points(72) = New Point(0, -10)
        points(73) = New Point(0, -10)
        points(74) = New Point(0, -10)
        points(75) = New Point(0, -10)
        points(76) = New Point(0, -10)
        points(77) = New Point(0, -10)
        points(78) = New Point(0, -10)
        points(79) = New Point(0, -10)
        points(80) = New Point(0, -10)
        points(81) = New Point(0, -10)
        points(82) = New Point(10, 0)
        points(83) = New Point(10, 0)
        points(84) = New Point(10, 0)
        points(85) = New Point(10, 0)
        points(86) = New Point(10, 0)
        points(87) = New Point(10, 0)
        points(88) = New Point(10, 0)
        points(89) = New Point(10, 0)
        points(90) = New Point(10, 0)
        points(91) = New Point(10, 0)
        points(92) = New Point(10, 0)
        points(93) = New Point(10, 0)
        points(94) = New Point(10, 0)
        points(95) = New Point(10, 0)
        points(96) = New Point(10, 0)
        points(97) = New Point(10, 0)
        points(98) = New Point(10, 0)
        points(99) = New Point(10, 0)
        points(100) = New Point(10, 0)
        points(101) = New Point(10, 0)
        points(102) = New Point(10, 0)
        'Don't change after here
        Integer.TryParse(obj.Tag, index)
        '  obj.Location = New Point(obj.Location.X + points(index).X, obj.Location.Y + points(index).Y)
        movexy(points(index).X, points(index).Y, obj)
        index = (index + 1) Mod points.Length
        obj.Tag = index
    End Sub
    Sub LeftRight4(obj As PictureBox)
        Dim index As Integer
        Dim points(100) As Point
        points(0) = New Point(-10, 0)
        points(1) = New Point(-10, 0)
        points(2) = New Point(-10, 0)
        points(3) = New Point(-10, 0)
        points(4) = New Point(-10, 0)
        points(5) = New Point(-10, 0)
        points(6) = New Point(-10, 0)
        points(7) = New Point(-10, 0)
        points(8) = New Point(-10, 0)
        points(9) = New Point(-10, 0)
        points(10) = New Point(-10, 0)
        points(11) = New Point(-10, 0)
        points(12) = New Point(-10, 0)
        points(13) = New Point(-10, 0)
        points(14) = New Point(-10, 0)
        points(15) = New Point(-10, 0)
        points(16) = New Point(-10, 0)
        points(17) = New Point(-10, 0)
        points(18) = New Point(-10, 0)
        points(19) = New Point(-10, 0)
        points(20) = New Point(0, -10)
        points(21) = New Point(0, -10)
        points(22) = New Point(0, -10)
        points(23) = New Point(0, -10)
        points(24) = New Point(0, -10)
        points(25) = New Point(0, -10)
        points(26) = New Point(0, -10)
        points(27) = New Point(0, -10)
        points(28) = New Point(0, -10)
        points(29) = New Point(0, -10)
        points(30) = New Point(0, -10)
        points(31) = New Point(0, -10)
        points(32) = New Point(0, -10)
        points(33) = New Point(0, -10)
        points(34) = New Point(0, -10)
        points(35) = New Point(0, -10)
        points(36) = New Point(0, -10)
        points(37) = New Point(0, -10)
        points(38) = New Point(0, -10)
        points(39) = New Point(0, -10)
        points(40) = New Point(0, -10)
        points(41) = New Point(0, -10)
        points(42) = New Point(0, -10)
        points(43) = New Point(0, -10)
        points(44) = New Point(0, -10)
        points(45) = New Point(0, -10)
        points(46) = New Point(0, -10)
        points(47) = New Point(0, -10)
        points(48) = New Point(0, -10)
        points(49) = New Point(0, -10)
        points(50) = New Point(10, 0)
        points(51) = New Point(10, 0)
        points(52) = New Point(10, 0)
        points(53) = New Point(10, 0)
        points(54) = New Point(10, 0)
        points(55) = New Point(10, 0)
        points(56) = New Point(10, 0)
        points(57) = New Point(10, 0)
        points(58) = New Point(10, 0)
        points(59) = New Point(10, 0)
        points(60) = New Point(10, 0)
        points(61) = New Point(10, 0)
        points(62) = New Point(10, 0)
        points(63) = New Point(10, 0)
        points(64) = New Point(10, 0)
        points(65) = New Point(10, 0)
        points(66) = New Point(10, 0)
        points(67) = New Point(10, 0)
        points(68) = New Point(10, 0)
        points(69) = New Point(10, 0)
        points(70) = New Point(0, 10)
        points(71) = New Point(0, 10)
        points(72) = New Point(0, 10)
        points(73) = New Point(0, 10)
        points(74) = New Point(0, 10)
        points(75) = New Point(0, 10)
        points(76) = New Point(0, 10)
        points(77) = New Point(0, 10)
        points(78) = New Point(0, 10)
        points(79) = New Point(0, 10)
        points(80) = New Point(0, 10)
        points(81) = New Point(0, 10)
        points(82) = New Point(0, 10)
        points(83) = New Point(0, 10)
        points(84) = New Point(0, 10)
        points(85) = New Point(0, 10)
        points(86) = New Point(0, 10)
        points(87) = New Point(0, 10)
        points(88) = New Point(0, 10)
        points(89) = New Point(0, 10)
        points(90) = New Point(0, 10)
        points(91) = New Point(0, 10)
        points(92) = New Point(0, 10)
        points(93) = New Point(0, 10)
        points(94) = New Point(0, 10)
        points(95) = New Point(0, 10)
        points(96) = New Point(0, 10)
        points(97) = New Point(0, 10)
        points(98) = New Point(0, 10)
        points(99) = New Point(0, 10)
        'Don't change after here
        Integer.TryParse(obj.Tag, index)
        '  obj.Location = New Point(obj.Location.X + points(index).X, obj.Location.Y + points(index).Y)
        movexy(points(index).X, points(index).Y, obj)
        index = (index + 1) Mod points.Length
        obj.Tag = index
    End Sub
    Sub LeftRight5(obj As PictureBox)
        Dim index As Integer
        Dim points(103) As Point
        points(0) = New Point(0, -10)
        points(1) = New Point(0, -10)
        points(2) = New Point(0, -10)
        points(3) = New Point(0, -10)
        points(4) = New Point(0, -10)
        points(5) = New Point(0, -10)
        points(6) = New Point(0, -10)
        points(7) = New Point(0, -10)
        points(8) = New Point(0, -10)
        points(9) = New Point(0, -10)
        points(10) = New Point(0, -10)
        points(11) = New Point(0, -10)
        points(12) = New Point(0, -10)
        points(13) = New Point(0, -10)
        points(14) = New Point(0, -10)
        points(15) = New Point(0, -10)
        points(16) = New Point(0, -10)
        points(17) = New Point(0, -10)
        points(18) = New Point(0, -10)
        points(19) = New Point(0, -10)
        points(20) = New Point(0, -10)
        points(21) = New Point(0, -10)
        points(22) = New Point(0, -10)
        points(23) = New Point(0, -10)
        points(24) = New Point(0, -10)
        points(25) = New Point(0, -10)
        points(26) = New Point(0, -10)
        points(27) = New Point(0, -10)
        points(28) = New Point(0, -10)
        points(29) = New Point(0, -10)
        points(30) = New Point(10, 0)
        points(31) = New Point(10, 0)
        points(32) = New Point(10, 0)
        points(33) = New Point(10, 0)
        points(34) = New Point(10, 0)
        points(35) = New Point(10, 0)
        points(36) = New Point(10, 0)
        points(37) = New Point(10, 0)
        points(39) = New Point(10, 0)
        points(40) = New Point(10, 0)
        points(41) = New Point(10, 0)
        points(42) = New Point(10, 0)
        points(43) = New Point(10, 0)
        points(44) = New Point(10, 0)
        points(45) = New Point(10, 0)
        points(46) = New Point(10, 0)
        points(47) = New Point(10, 0)
        points(48) = New Point(10, 0)
        points(49) = New Point(10, 0)
        points(50) = New Point(10, 0)
        points(51) = New Point(10, 0)
        points(52) = New Point(0, 10)
        points(53) = New Point(0, 10)
        points(54) = New Point(0, 10)
        points(55) = New Point(0, 10)
        points(56) = New Point(0, 10)
        points(57) = New Point(0, 10)
        points(58) = New Point(0, 10)
        points(59) = New Point(0, 10)
        points(60) = New Point(0, 10)
        points(61) = New Point(0, 10)
        points(62) = New Point(0, 10)
        points(63) = New Point(0, 10)
        points(64) = New Point(0, 10)
        points(65) = New Point(0, 10)
        points(66) = New Point(0, 10)
        points(67) = New Point(0, 10)
        points(68) = New Point(0, 10)
        points(69) = New Point(0, 10)
        points(70) = New Point(0, 10)
        points(71) = New Point(0, 10)
        points(72) = New Point(0, 10)
        points(73) = New Point(0, 10)
        points(74) = New Point(0, 10)
        points(75) = New Point(0, 10)
        points(76) = New Point(0, 10)
        points(77) = New Point(0, 10)
        points(78) = New Point(0, 10)
        points(79) = New Point(0, 10)
        points(80) = New Point(0, 10)
        points(81) = New Point(0, 10)
        points(82) = New Point(-10, 0)
        points(83) = New Point(-10, 0)
        points(84) = New Point(-10, 0)
        points(85) = New Point(-10, 0)
        points(86) = New Point(-10, 0)
        points(87) = New Point(-10, 0)
        points(88) = New Point(-10, 0)
        points(89) = New Point(-10, 0)
        points(90) = New Point(-10, 0)
        points(91) = New Point(-10, 0)
        points(92) = New Point(-10, 0)
        points(93) = New Point(-10, 0)
        points(94) = New Point(-10, 0)
        points(95) = New Point(-10, 0)
        points(96) = New Point(-10, 0)
        points(97) = New Point(-10, 0)
        points(98) = New Point(-10, 0)
        points(99) = New Point(-10, 0)
        points(100) = New Point(-10, 0)
        points(101) = New Point(-10, 0)
        points(102) = New Point(-10, 0)
        'Don't change after here
        Integer.TryParse(obj.Tag, index)
        '  obj.Location = New Point(obj.Location.X + points(index).X, obj.Location.Y + points(index).Y)
        movexy(points(index).X, points(index).Y, obj)
        index = (index + 1) Mod points.Length
        obj.Tag = index
    End Sub
    Sub Right(obj As PictureBox)
        Dim index As Integer
        Dim points(2) As Point
        points(0) = New Point(20, 0)
        points(1) = New Point(20, 0)
        'Don't change after here
        Integer.TryParse(obj.Tag, index)
        '  obj.Location = New Point(obj.Location.X + points(index).X, obj.Location.Y + points(index).Y)
        movexy(points(index).X, points(index).Y, obj)
        index = (index + 1) Mod points.Length
        obj.Tag = index
    End Sub
    Private Sub Timer1_Tick(sender As Object, e As EventArgs) Handles Timer1.Tick
        Right(B1)
    End Sub
End Class